[package]
name = "gs-diagnostics"
version = "0.1.0"
edition = { workspace = true }
build = "build.rs"

[dependencies]
shadow-rs = { workspace = true }
tower-lsp-server = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }

gs-ast = { workspace = true }
gs-parser = { workspace = true }
gs-util = { workspace = true }
pest = { workspace = true }

[build-dependencies]
shadow-rs = { version = "1.7" }