use pest_derive::Parser;

/// The Game Script parser implementation.
///
/// This struct is generated by `pest` and provides the entry point for parsing
/// GS code according to the grammar defined in `gs/grammar.pest`.
#[derive(Parser)]
#[grammar = "gs/grammar.pest"]
pub struct GameScriptParser;
