[package]
name = "trainz-definition"
version = "0.1.0"
build = "build.rs"

edition.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
categories.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
shadow-rs = { workspace = true }
tower-lsp-server = { workspace = true }
tracing = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
dashmap = { workspace = true }

trainz-ast = { workspace = true }
trainz-soup-validators = { workspace = true }

[build-dependencies]
shadow-rs = { version = "1.7" }

[dev-dependencies]
trainz-parser = { workspace = true }
env_logger = { workspace = true }
tempfile = { workspace = true }
