[package]
name = "trainz-hover"
version = "0.1.0"
build = "build.rs"

edition.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
categories.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
shadow-rs = { workspace = true, features = ["metadata"] }
tower-lsp-server = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }

trainz-ast = { workspace = true }
trainz-acs-text-validators = { workspace = true }
trainz-definition = { workspace = true }

[build-dependencies]
shadow-rs = { workspace = true, features = ["build", "git2"] }

[dev-dependencies]
trainz-parser = { workspace = true }
