[package]
name = "trainz-hover"
version = "0.1.0"
edition.workspace = true

[dependencies]
shadow-rs = { workspace = true }
tower-lsp-server = { workspace = true }
log = { workspace = true }

trainz-ast = { workspace = true }
trainz-soup-validators = { workspace = true }
trainz-common = { workspace = true }

[build-dependencies]
shadow-rs = { version = "1.7" }

[dev-dependencies]
trainz-parser = { workspace = true }
