[workspace]
members = [
    "crates/ast",
    "crates/common",
    "crates/formatter",
    "crates/formatter-cli",
    "crates/diagnostics",
    "crates/language-server",
    "crates/parser",
    "crates/semantic-tokens",
    "crates/symboliser",
    "crates/completions",
    "crates/folding",
    "crates/hover",
    "crates/definition",
    "crates/soup-validators"
]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"
[workspace.dependencies]
# External dependencies
shadow-rs = { version = "1.7", default-features = false }
tokio = { version = "1.51", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = [] }
bson = { version = "3.1", features = ["chrono-0_4", "serde"] }
sha2 = { version = "0.11", features = [] }
hex = { version = "0.4", features = [] }
thiserror = { version = "2.0", features = [] }
anyhow = { version = "1.0", features = [] }
log = { version = "0.4", features = [] }
env_logger = { version = "0.11", features = ["auto-color"] }
async-trait = { version = "0.1", features = [] }
rayon = { version = "1.11", features = [] }
chrono = { version = "0.4", features = ["serde"] }
pest = { version = "2.8", features = ["pretty-print"] }
tower-lsp-server = { version = "0.23", features = [] }
clap = { version = "4.6", features = ["derive", "env"] }
clio = { version = "0.3", features = ["clap-parse"] }
clap-verbosity-flag = { version = "3.0.4", features = ["serde"] }
criterion = { version = "0.8.2", features = ["async_tokio", "rayon"] }
dashmap = { version = "7.0.0-rc2", features = ["rayon", "serde", "typesize"] }

# Internal workspace dependencies
trainz-ast = { path = "crates/ast", version = "0.1.0" }
trainz-common = { path = "crates/common", version = "0.1.0" }
trainz-parser = { path = "crates/parser", version = "0.1.0" }
trainz-diagnostics = { path = "crates/diagnostics", version = "0.1.0" }
trainz-formatter = { path = "crates/formatter", version = "0.1.0" }
trainz-language-server = { path = "crates/language-server", version = "0.1.0" }
trainz-semantic-tokens = { path = "crates/semantic-tokens", version = "0.1.0" }
trainz-symboliser = { path = "crates/symboliser", version = "0.1.0" }
trainz-completions = { path = "crates/completions", version = "0.1.0" }
trainz-folding = { path = "crates/folding", version = "0.1.0" }
trainz-hover = { path = "crates/hover", version = "0.1.0" }
trainz-definition = { path = "crates/definition", version = "0.1.0" }
trainz-soup-validators = { path = "crates/soup-validators", version = "0.1.0" }
