[package]
name = "gs-completions"
version = "0.1.0"
edition.workspace = true

[dependencies]
shadow-rs = { workspace = true }
tower-lsp-server = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
gs-ast = { workspace = true }
gs-diagnostics = { workspace = true }
gs-parser = { workspace = true }

[build-dependencies]
shadow-rs = { version = "1.7" }
