[package]
name = "trainz-completions"
version = "0.1.0"
build = "build.rs"

edition.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
categories.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
shadow-rs = { workspace = true }
tower-lsp-server = { workspace = true }
tracing = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }

trainz-ast = { workspace = true }
trainz-acs-text-validators = { workspace = true }
trainz-parser = { workspace = true }
trainz-common = { workspace = true }

[build-dependencies]
shadow-rs = { version = "1.7" }
