[package]
name = "trainz-fmt"
version = "0.1.0"
build = "build.rs"

edition.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
categories.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
shadow-rs = { workspace = true }

clap = { workspace = true }
clio = { workspace = true }
clap-verbosity-flag = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
log = { workspace = true }

trainz-ast = { workspace = true }
trainz-common = { workspace = true }
trainz-parser = { workspace = true }
trainz-formatter = { workspace = true }

[build-dependencies]
shadow-rs = { version = "1.7" }