[package]
name = "trainz-ast"
version = "0.1.0"
edition.workspace = true
build = "build.rs"

[dependencies]
shadow-rs = { workspace = true, features = ["metadata"] }
pest = { workspace = true }
tower-lsp-server = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
bson = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

trainz-parser = { workspace = true }
trainz-common = { workspace = true }
tracing = { workspace = true }

criterion = { workspace = true }

[build-dependencies]
shadow-rs = { workspace = true, features = ["build", "git2"] }
