[package]
name = "trainz-parser"
version = "0.1.0"
build = "build.rs"

edition.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
categories.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
shadow-rs = { workspace = true }
thiserror = { workspace = true }
pest = { workspace = true }
pest_derive = { version = "2.8" }
lazy_static = { version = "1.5", features = [] }

[build-dependencies]
shadow-rs = { version = "1.7" }
