[package]
name = "trainz-language-server"
version = "0.1.0"
build = "build.rs"

edition.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
categories.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
shadow-rs = { workspace = true }
tower-lsp-server = { workspace = true }

tokio = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }
futures = { workspace = true }

dashmap = { workspace = true }
walkdir = { workspace = true }
rusqlite = { workspace = true }
async-recursion = { version = "1.1", features = [] }

clap = { workspace = true }
clap-verbosity-flag = { workspace = true }

trainz-ast = { workspace = true }
trainz-parser = { workspace = true }
trainz-folding = { workspace = true }
trainz-common = { workspace = true }
trainz-diagnostics = { workspace = true }
trainz-acs-text-validators = { workspace = true }
trainz-semantic-tokens = { workspace = true }
trainz-symboliser = { workspace = true }
trainz-completions = { workspace = true }
trainz-definition = { workspace = true }
trainz-hover = { workspace = true }
trainz-tdx = { workspace = true }
num_cpus = "1.17.0"

[dev-dependencies]
criterion = { workspace = true }
futures = "0.3"

[[bench]]
name = "process_gs_file"
harness = false

[[bench]]
name = "process_acs_text_file"
harness = false

[build-dependencies]
shadow-rs = { version = "1.7" }