[package]
name = "trainz-language-server"
version = "0.1.0"
edition.workspace = true
build = "build.rs"

[dependencies]
shadow-rs = { workspace = true }
tower-lsp-server = { workspace = true }

tokio = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }

dashmap = { workspace = true }
async-recursion = { version = "1.1", features = [] }

clap = { workspace = true }
clap-verbosity-flag = { workspace = true }

trainz-ast = { workspace = true }
trainz-parser = { workspace = true }
trainz-folding = { workspace = true }
trainz-common = { workspace = true }
trainz-diagnostics = { workspace = true }
trainz-soup-validators = { workspace = true }
trainz-semantic-tokens = { workspace = true }
trainz-symboliser = { workspace = true }
trainz-completions = { workspace = true }
trainz-definition = { workspace = true }
trainz-hover = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "process_gs_file"
harness = false

[[bench]]
name = "process_soup_file"
harness = false

[build-dependencies]
shadow-rs = { version = "1.7" }