[package]
name = "trainz-acs-text-validators"
version = "0.1.0"
build = "build.rs"

edition.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
categories.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
shadow-rs = { workspace = true }

trainz-ast = { workspace = true }
trainz-parser = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
async-recursion = { workspace = true }

[build-dependencies]
shadow-rs = { version = "1.7" }

[dev-dependencies]
tempfile.workspace = true