[package]
name = "trainz-tdx"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
categories.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
trainz-common = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
