WHITESPACE = _{ " " | "\t" }

newline = _{ "\r\n" | "\n" | "\r" }

line_comment  = _{ (";" ~ (!newline ~ ANY)*) }
block_comment = _{ "/*" ~ (block_comment | !"*/" ~ ANY)* ~ "*/" }

COMMENT = _{ line_comment | block_comment }

acs_text = _{ SOI ~ newline* ~ (key_value_pair | error_recovery_acs_text)* ~ newline* ~ EOI }
error_recovery_acs_text = _{ !key ~ !brace_close ~ !EOI ~ ANY }

key_value_pair = { #tag = key ~ value? ~ newline* }

key = @{ (ASCII_ALPHANUMERIC | "/" | "_" | "-" | ".")+ }

value = { (string_value | array_value | numeric_value | variable_value | kuid_value | container_value) ~ newline? }

variable = @{ (ASCII_ALPHANUMERIC | "/" | "_" | "-" | "$" | " " | "&" | "(" | ")" | "." | ",")+ }

variable_value = @{ #tag = variable }

number  = _{ ASCII_DIGIT+ }
integer = @{ "-"? ~ number }

hex = @{ ("0x" | "0X") ~ ASCII_HEX_DIGIT+ }

float = @{
    "-"? ~ ((number ~ "." ~ number?) | (number? ~ "." ~ number)) ~ ("e+" ~ number)? ~ "f"?
}

numeric_value = { float | hex | integer }

array_value = { numeric_value ~ ("," ~ numeric_value)+ }

string_value = { double_quote ~ string ~ double_quote }
string       = @{ (!(double_quote | "\\") ~ ANY)* ~ (escape ~ string)? }

escape  = @{ "\\" ~ (double_quote | "\\" | "/" | "b" | "f" | "n" | "r" | "t" | unicode) }
unicode = @{ "u" ~ ASCII_HEX_DIGIT{4} }

kuid_value = { angle_open ~ (kuid2_internal | kuid_interal) ~ angle_close }

kuid_interal   = _{ ^"KUID" ~ colon ~ kuid_user_id ~ colon ~ kuid_content_id }
kuid2_internal = _{ ^"KUID2" ~ colon ~ kuid_user_id ~ colon ~ kuid_content_id ~ colon ~ kuid_version_number }

kuid_user_id = @{ "-"? ~ ASCII_DIGIT+ }
// Content ID does not support negative numbers: https://online.ts2009.com/mediaWiki/index.php/KUID#Content_ID_Number
kuid_content_id     = @{ "-"? ~ ASCII_DIGIT+ }
kuid_version_number = @{ ASCII_DIGIT+ }

container_value = { newline* ~ brace_open ~ newline* ~ (key_value_pair | error_recovery_acs_text)* ~ newline* ~ brace_close }

double_quote = @{ "\"" }
colon        = @{ ":" }

brace_open  = @{ "{" }
brace_close = @{ "}" }
angle_open  = @{ "<" }
angle_close = @{ ">" }
