[package]
name = "trainz-common"
version = "0.1.0"
build = "build.rs"

edition.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
categories.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
shadow-rs = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
pest = { workspace = true }
tower-lsp-server = { workspace = true }

[build-dependencies]
shadow-rs = { version = "1.7" }