[package]
name = "trainz-symboliser"
version = "0.1.0"

edition.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
categories.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
shadow-rs = { workspace = true, features = ["metadata"] }
tower-lsp-server = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }

trainz-ast = { workspace = true }
trainz-common = { workspace = true }

[build-dependencies]
shadow-rs = { workspace = true, features = ["build", "git2"] }

[dev-dependencies]
trainz-parser = { workspace = true }
pest = { workspace = true }
